name: phpcs

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
  push:
    branches:
      - dev
      - master

jobs:
  phpcs:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest]
        php-versions: ['8.1']
    name: running on ${{ matrix.operating-system }} / PHP v${{ matrix.php-versions }}

    steps:
      - uses: actions/checkout@v3

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

      - name: Install Composer dependencies
        run: composer install -o

      - name: Run phpcs tool
        run: vendor/bin/phpcs src tests --standard=PSR2 -p -n
