name: phpmd

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
  push:
    branches:
      - dev
      - master

jobs:
  phpmd:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest, windows-latest, macOS-latest]
        php-versions: ['7.2']
    name: Run phpmd on PHP ${{ matrix.php-versions }} / ${{ matrix.operating-system }}

    steps:
      - uses: actions/checkout@v3

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

      - name: Install Composer dependencies
        run: composer install -o

      - name: Run phpmd tool
        run: vendor/bin/phpmd src text unusedcode,cleancode,controversial
